baseURL = "https://blog.eula.no/"
languageCode = "en-us"
title = "blog.eula.no"
theme = ["hugo-notice", "gokarna"]
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of monokai, emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Eskil Uhlving Larsen"
  description = "Azure | AWS | IaC | DevOps | Powershell"
  avatarURL = "/images/headshot.jpeg"
  AvatarAltText = "avatar"
  avatarSize = "size-l"
  customCommentHTML = """
<script src="https://giscus.app/client.js"
        data-repo="picccard/blog"
        data-repo-id="R_kgDOLuCJfQ"
        data-category="General"
        data-category-id="DIC_kwDOLuCJfc4ChWvV"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="preferred_color_scheme"
        data-lang="en"
        data-loading="lazy"
        crossorigin="anonymous"
        async>
</script>
"""
  dateFormat = "2 January, 2006"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  socialIcons = [
    {name = "github", url = "https://github.com/picccard"},
    {name = "linkedin", url = "https://www.linkedin.com/in/eskil-larsen-a15479175/"},
    {name = "rss", url = "/index.xml"}
  ]
  togglePreviousAndNextButtons = "true"
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/picccard"
    weight = 4

  [[menu.main]]
    identifier = "linkedin"
    pre = "<span data-feather='linkedin'></span>"
    url = "https://www.linkedin.com/in/eskil-larsen-a15479175/"
    weight = 5

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 6

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
